find . -name "*.bak" | xargs rm -rf 
find . -name "*.ddk" | xargs rm -rf 
find . -name "*.edk" | xargs rm -rf 
find . -name "*.lst" | xargs rm -rf 
find . -name "*.lnp" | xargs rm -rf 
find . -name "*.mpf" | xargs rm -rf 
find . -name "*.mpj" | xargs rm -rf 
find . -name "*.obj" | xargs rm -rf 
find . -name "*.omf" | xargs rm -rf 
find . -name "*.opt" | xargs rm -rf 
find . -name "*.plg" | xargs rm -rf 
find . -name "*.rpt" | xargs rm -rf 
find . -name "*.tmp" | xargs rm -rf 
find . -name "*.__i" | xargs rm -rf 
find . -name "*.crf" | xargs rm -rf 
find . -name "*.o" | xargs rm -rf 
find . -name "*.d" | xargs rm -rf 
find . -name "*.axf" | xargs rm -rf 
find . -name "*.tra" | xargs rm -rf 
find . -name "*.dep" | xargs rm -rf 
find . -name "*.JLinkLog.txt" | xargs rm -rf 
find . -name "*.iex" | xargs rm -rf 
find . -name "*.htm" | xargs rm -rf 
find . -name "*.sct" | xargs rm -rf 
find . -name "*.map" | xargs rm -rf 
find . -name "*.orig" | xargs rm -rf 
exit